name: Cancelling Duplicates
on:
  workflow_run:
    workflows: 
      - 'CI - Build - MacOS'
      - 'CI - CPP, Python Tests'
      - 'CI - Go Functions style check'
      - 'CI - Go Functions Tests'
      - 'CI - Integration - Backwards Compatibility'
      - 'CI - Integration - Cli'
      - 'CI - Integration - Function State'
      - 'CI - Integration - Messaging'
      - 'CI - Integration - Process'
      - 'CI - Integration - Schema'
      - 'CI - Integration - Sql'
      - 'CI - Integration - Standalone'
      - 'CI - Integration - Thread'
      - 'CI - Integration - Tiered FileSystem'
      - 'CI - Integration - Tiered JCloud'
      - 'CI - Integration - Transaction'
      - 'CI - Misc'
      - 'CI - Pulsar Website build'
      - 'Pulsar Bot'
      - 'CI - Shade - Test'
      - 'CI - Unit - Brokers - Broker Group 1'
      - 'CI - Unit - Brokers - Broker Group 2'
      - 'CI - Unit - Brokers - Client Api'
      - 'CI - Unit - Brokers - Client Impl'
      - 'CI - Unit - Brokers - Other'
      - 'CI - Unit - Proxy'
      - 'CI - Unit'
    types: ['requested']

jobs:
  cancel-duplicate-workflow-runs:
    name: "Cancel duplicate workflow runs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout potiuk/cancel-workflow-runs
        with:
          repository: potiuk/cancel-workflow-runs
          path: ./build/.actions/potiuk/cancel-workflow-runs
          ref: 953e057dc81d3458935a18d1184c386b0f6b5738 # @master
          fetch-depth: 1
      - uses: ./build/.actions/potiuk/cancel-workflow-runs
        name: "Cancel duplicate workflow runs"
        with:
          cancelMode: allDuplicates
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}
