#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

trigger:
- master

jobs:
- job: Unit_Tests
  timeoutInMinutes: 180
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      export MAVEN_OPTS="-Xmx4096m"
      ./mvnw -Ddeflaker.rerunFlakies=1 install

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

- job: Integration_Tests
  timeoutInMinutes: 180
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      ./tests/scripts/pre-integ-tests.sh
      ./mvnw -B install -Pdocker -DskipTests
      ./mvnw -B -f tests/pom.xml test -DintegrationTests
      ./tests/scripts/post-integ-tests.sh

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

- job: CPP_Tests
  timeoutInMinutes: 180
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      ./mvnw -B clean package -DskipTests
      echo "Build C++ client library"
      export CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Debug -DBUILD_DYNAMIC_LIB=OFF"
      pulsar-client-cpp/docker-build.sh
      pulsar-client-cpp/docker-tests.sh



