apiVersion: v1
kind: Pod
metadata:
  name: pulsar-cluster-metadata-init
  labels:
    app: pulsar
    component: broker
  spec:
    initContainers:
      - name: pulsar-init-container
        image: apachepulsar/pulsar:latest
        command: ["sh", "-c"]
        args:
          - >
            bin/apply-config-from-env.py conf/broker.conf &&
            bin/pulsar initialize-cluster-metadata \
                --cluster us-central \
                --zookeeper zookeeper \
                --global-zookeeper zookeeper \
                --web-service-url http://broker.default.svc.cluster.local:8080/ \
                --broker-service-url pulsar://broker.default.svc.cluster.local:6650/ || true;