name: 'Tune OS performance'
description: 'tunes the operation system performance related parameters for maximum performance'
runs:
  using: "composite"
  steps:
    - run: |
        sudo mount -o remount,nodiscard,commit=999999,nobarrier /
        sudo mount -o remount,nodiscard,commit=999999,nobarrier /mnt
        echo 1 | sudo tee /proc/sys/vm/swappiness
        echo madvise | sudo tee /sys/kernel/mm/transparent_hugepage/enabled
      shell: bash
