configs:
- name: workerId
  default: standalone
- name: workerHostname
  default: localhost
- name: workerPort
  default: 6750
- name: functionMetadataTopicName
  default: metadata
- name: functionMetadataSnapshotsTopicPath
  default: snapshots
- name: clusterCoordinationTopicName
  default: coordinate
- name: pulsarFunctionsNamespace
  default: public/functions
- name: pulsarFunctionsCluster
  default: standalone
- name: pulsarServiceUrl
  default: pulsar://localhost:6650
- name: pulsarWebServiceUrl
  default: http://localhost:8080
- name: numFunctionPackageReplicas
  default: 1
- name: downloadDirectory
  default: /tmp/pulsar_functions
- name: processContainerFactory
- name: logDirectory
- name: schedulerClassName
  default: org.apache.pulsar.functions.worker.scheduler.RoundRobinScheduler
- name: functionAssignmentTopicName
  default: assignments
- name: failureCheckFreqMs
  default: 30000
- name: rescheduleTimeoutMs
  default: 60000
- name: initialBrokerReconnectMaxRetries
  default: 60
- name: assignmentWriteMaxRetries
  default: 60
- name: instanceLivenessCheckFreqMs
  default: 30000